# docker-compose.prod.yml

services:
    db:
        image: postgres:15
        env_file: .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        env_file: .env
        ports:
            - "5050:80"
        depends_on:
            - db
        volumes:
            - pgadmin_data:/var/lib/pgadmin

    web:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        env_file: .env
        ports:
            - "8000:8000"
        depends_on:
            - db
        restart: always

    redis:
        image: redis:7

    celery:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        command: celery -A myproject worker --loglevel=info
        depends_on:
            - redis
            - web
        env_file: .env

    beat:
        build:
            context: ./backend
            dockerfile: Dockerfile.prod
        command: celery -A myproject beat --loglevel=info
        depends_on:
            - redis
            - web
        env_file: .env

volumes:
    postgres_data:
    pgadmin_data:
